### PR TITLE
Making the code consistent

### PR DESCRIPTION
**Pull request by httpstersk**
... and a little bit prettier ✨

### CODE REVIEW

**Comment by VRamazing** [comment]
@Jake0Tron  Could you please review and resolve the conflicts

**Comment by Jake0Tron** [comment]
What am I resolving? I haven't contributed to this branch..?

**Comment by Jake0Tron** [comment]
Might be worth an eslint to keep things nice over time rather than pr's ...

**Comment by VRamazing** [comment]
Sorry @Jake0Tron My fault

**Pull request merged**
