### PR TITLE
WIP: Add ball control to paddle - issue#2

### PR DESCRIPTION
**Pull request by choudhary001**
Angle of return is constant at 30 degrees taken w.r.t. paddle as base

### CODE REVIEW

**Comment by VRamazing** [comment]
@brunolm  Could you please review this

**Comment by brunolm** [comment]
Looks good to me 👍

**Comment by choudhary001** [comment]
@VRamazing Hey i have fixed the merge conflicts. Can you please review this?

**Comment by VRamazing** [comment]
@choudhary001  I am on it

**Comment by VRamazing** [comment]
@choudhary001  The paddle should reflect the ball based on from what part of paddle the user hits it.Currently, even if you hit the paddle with right-hand corner it is reflected across x-axis ( The x component of ball motion vector remains same).I want the ball to retrace the path it came from when i hit it with the corner. Check this [Image](https://www.google.co.in/search?biw=1203&bih=553&tbm=isch&sa=1&q=breakout+paddle+refect+diagram&oq=breakout+paddle+refect+diagram&gs_l=psy-ab.3...3989.5247.0.5646.9.8.0.0.0.0.445.847.4-2.2.0....0...1.1.64.psy-ab..9.0.0....0.x5u7P7xyk8k#imgrc=ME3kIH8LVxf9cM:)
You can use the distance between the center of paddle and corner of the paddle to determine x and y component of ball motion.

**Pull request closed without merging**
