### PR TITLE
added lives to player so they have 3 attempts to play

### PR DESCRIPTION
**Pull request by Jake0Tron**

### CODE REVIEW

**Comment by VRamazing** [comment]
Please don't change paddle ball collision function.They have been set after a lot of tweaking.Your code has reintroduced some bugs.

**Review by VRamazing — COMMENTED** [review]
Rename gameReset to a different function.It may lead to confusion between two function.
Reimplement the previous code for ball paddle collision
Position lives text in lower left corner .Its should be displayed beneath paddle.(Paddle must overlay over it).Apply padding as necessary make it look good.

**Comment by Jake0Tron** [comment]
updated

**Comment by VRamazing** [comment]
This is not what I wanted but it sure looks cool :+1:

**Pull request merged**
