### PR TITLE
Made a small change to the collision detection between the ball and the paddle

### PR DESCRIPTION
**Pull request by cynthiajbuck**
I changed the if statement on line 187 so that if the bottom of the
ball hit the paddle, the ball would change direction.
I could do the same type of thing to the walls, but I wanted to make
sure that I’m not fixing something that ain’t broken first.

### CODE REVIEW

**Comment by VRamazing** [comment]
@cynthiajbuck  Could you resolve the conflicts

**Review by VRamazing — CHANGES_REQUESTED** [review]
//!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!BE SURE TO SET THESE BACK TO -5 BEFORE YOU GOGO

Please remove unnecessary comments and fetch and merge updated source repo.

**Review by VRamazing — CHANGES_REQUESTED** [review]
I love your change.Although I can't merge it as it has a lot of redundant code.It seems you haven't merged the base fork properly.Please fix the issue.
Just a side note.As this is a small change to the codebase.An easier and faster approach would be to make a brand new fork, do the required change and make a new PR.You can do whatever you are comfortable with

**Comment by cynthiajbuck** [comment]
I just made a new fork and did a new PR. thank you!

**Comment by VRamazing** [comment]
Thank you @cynthiajbuck  I have merged. Hopefully, you will contribute more to this repo and we can grow together.

**Pull request closed without merging**
